name: iConomy
main: com.iConomy.iConomy
version: 5.01
authors: [Nijikokun,ElgarL]
load: startup
commands:
    money:
        description: Controls account balances and more
        usage: /money
    bank:
        description: Control, list, create, and do various bank features.
        usage: /bank